name: SurveyBear CI/CD

on:
  push:
    branches:
      - test-branch
    paths:
      - apps/surveybear-survey-spa/**
      - libs/**
jobs:
  test_jobSpa:
    runs-on: ubuntu-latest
    name: Test Spa

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
      - run: npm install
      - run: npx nx test surveybear-survey-spa
