name: SurveyBear CI/CD
on:
  push:
    branches:
      - test-branch
    paths:
      - apps/surveybear-api/**
      - libs/**
jobs:
  testing_api:
    runs-on: ubuntu-latest
    name: testing api

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
      - run: npm install
      - run: npx nx test surveybear-api
